name: task_management_application
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.0
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  firebase_storage: ^13.0.3
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  uuid: ^4.5.1
  universal_platform: ^1.1.0
  intl: ^0.20.2
  fl_chart: ^0.68.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  csv: ^6.0.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.3.0
  cloud_functions: ^6.0.5
  open_file: ^3.5.10
  web: ^1.1.1
  shared_preferences: ^2.5.4
  local_auth: 2.2.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:

 
  uses-material-design: true

  assets:
    - assets/
 